Fix: compiler args (#5752)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,10 +26,10 @@ jobs:
     - name: Download Compiler
       run: |
         echo "⬇️ Downloading compiler"
-        curl -L -o .bin/compiler "https://github.com/VATSIM-UK/sector-file-compiler/releases/latest/download/cli-linux-x64" || {
+        curl -L --output compiler "https://github.com/VATSIM-UK/sector-file-compiler/releases/latest/download/cli-linux-x64" || {
           echo "❌ Compiler download failed"; exit 1;
         }
-        chmod +x .bin/compiler || { echo "❌ Failed to make compiler executable"; exit 1; }
+        chmod +x ./compiler || { echo "❌ Failed to make compiler executable"; exit 1; }
 
     - name: Set Build Version
       run: echo "SECTORFILE_BUILD_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
@@ -41,7 +41,7 @@ jobs:
       run: |
         set -euo pipefail
         echo "🛠️ Compiling sector file"
-        .bin/compiler compile --config compiler-config.json $STRIP_COMMENTS --build-version "$SECTORFILE_BUILD_VERSION" || {
+        ./compiler --config-file compiler.config.json --strip-comments --no-wait --build-version $SECTORFILE_BUILD_VERSION $STRIP_COMMENTS
           echo "❌ Compilation failed"; exit 1;
         }
 
