Fix: Start SSH agent before push (#5774)
* cicd: Add debug logging

* cicd: add ssh agent to push stage

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -95,18 +95,17 @@ jobs:
         ssh-add - <<< "${{ secrets.DOCS_DEPLOY_KEY }}"
         mkdir -p ~/.ssh
         ssh-keyscan github.com >> ~/.ssh/known_hosts
-        echo "📥 Cloning Docs Website"
-        git clone git@github.com:VATSIM-UK/atc-documentation.git atc-documentation || {
-          echo "❌ Failed to clone documentation repo"; exit 1;
-        }
 
-    - name: SSH Debug
-      run: |
         echo "Loaded SSH Keys:"
         ssh-add -l || echo "No SSH keys loaded"
 
         echo "Testing SSH connection to GitHub"
         ssh -T git@github.com || echo "SSH auth to GitHub failed!"
+
+        echo "📥 Cloning Docs Website"
+        git clone git@github.com:VATSIM-UK/atc-documentation.git atc-documentation || {
+          echo "❌ Failed to clone documentation repo"; exit 1;
+        }
 
     - name: Upload Sector Files
       run: |
@@ -131,6 +130,12 @@ jobs:
 
     - name: Commit Changes
       run: |
+        echo "Starting SSH agent"
+        eval "$(ssh-agent -s)"
+        ssh-add - <<< "${{ secrets.DOCS_DEPLOY_KEY }}"
+        mkdir -p ~/.ssh
+        ssh-keyscan github.com >> ~/.ssh/known_hosts
+
         cd atc-documentation
         git add .
         git commit -m "Upload Sector File ${AIRAC_DATE}"
